.TH "ALF_Dict" 3 "Wed Jul 18 2018" "Version 1.0" "ALF Standard Lib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ALF_Dict \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ALF_dict\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBnext\fP"
.br
.ti -1c
.RI "char * \fBkey\fP"
.br
.ti -1c
.RI "void * \fBvalue\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char* ALF_Dict::key"

.SS "void* ALF_Dict::next"

.SS "void* ALF_Dict::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for ALF Standard Lib from the source code\&.
