.TH "include/ALF_std_extra.h" 3 "Wed Jul 18 2018" "Version 1.0" "ALF Standard Lib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/ALF_std_extra.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ALF_common\&.h'\fP
.br
\fC#include 'ALF_dso_loader\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBALF_std_extra_major_version\fP   (1)"
.br
.ti -1c
.RI "#define \fBALF_std_extra_minor_version\fP   (0)"
.br
.ti -1c
.RI "#define \fBALF_std_extra_patch_version\fP   (0)"
.br
.ti -1c
.RI "#define \fBALF_std_extra_version\fP   (\fBALF_std_extra_major_version\&.ALF_std_extra_minor_version\fP)"
.br
.ti -1c
.RI "#define \fBALF_std_extra_version_str\fP   (\fBALF_STR\fP(\fBALF_std_extra_major_version\fP)'\&.'\fBALF_STR\fP(\fBALF_std_extra_minor_version\fP)'\&.'\fBALF_STR\fP(\fBALF_std_extra_patch_version\fP))"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ALF_std_extra_major_version   (1)"

.SS "#define ALF_std_extra_minor_version   (0)"

.SS "#define ALF_std_extra_patch_version   (0)"

.SS "#define ALF_std_extra_version   (\fBALF_std_extra_major_version\&.ALF_std_extra_minor_version\fP)"

.SS "#define ALF_std_extra_version_str   (\fBALF_STR\fP(\fBALF_std_extra_major_version\fP)'\&.'\fBALF_STR\fP(\fBALF_std_extra_minor_version\fP)'\&.'\fBALF_STR\fP(\fBALF_std_extra_patch_version\fP))"

.SH "Author"
.PP 
Generated automatically by Doxygen for ALF Standard Lib from the source code\&.
