.TH "src/ALF_bool.c" 3 "Wed Jul 18 2018" "Version 1.0" "ALF Standard Lib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ALF_bool.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ALF_bool\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBALF_true\fP (void)"
.br
.ti -1c
.RI "\fBbool\fP \fBALF_false\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBbool\fP ALF_false (void)"

.PP
.nf
7                     {
8     return false;
9 }
.fi
.SS "\fBbool\fP ALF_true (void)"

.PP
.nf
3                    {
4     return true;
5 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for ALF Standard Lib from the source code\&.
